### ISSUE TITLE
Option to hook into paperweight's reobfJar task

### ISSUE THREAD

**Issue by DerEchtePilz** [jpenilla/run-task#56]
As of version 2.3.0 running a server using the `runServer` task on 1.20.5+ fully ignores any `reobfJar` task that a plugin might depend on if paperweight is used.
I'd like to propose a new task that does not ignore the `reobfJar` task since you might want to update the `paperweight.paperDevBundle()` dependency to use the latest version but the plugin should still support earlier versions of the game.
The `runServer` task is convenient in that matter since you don't need to set up an extra folder to test the plugin but because both tasks that run a server now ignore the `reobfJar` task, setting up the extra folder becomes a necessity again.
Please consider my suggestion, because even though it may not make the most sense, there is still demand for a task that depends on the `reobfJar` task.

**Comment by jpenilla** [comment]
On 1.20.5+ it makes no sense to waste time obfuscating the jar in development just for it to be immediately deobfuscated. If you have an edge case setup where this makes sense somehow, you can disable plugin jar detection and configure the plugin jars collection yourself.

**Comment by DerEchtePilz** [comment]
> and configure the plugin jars collection yourself.

Would you be able to provide an example of how to do that?

**Comment by ineanto** [comment]
> > and configure the plugin jars collection yourself.
> 
> Would you be able to provide an example of how to do that?

After encountering the same issue as you and digging through @jpenilla 's code to figure out how it worked, this is what I've came up with:

1. First, disable the plugin detection in your ```build.gradle.kts```:
```kotlin
extensions.configure<RunExtension> {
    disablePluginJarDetection()
}
```

2. Add this line in your ```runServer``` task:
```kotlin
 args("-add-plugin=${reobfJar.get().outputJar.path.toAbsolutePath()}")
```

This should now get the __obfuscated__ _(+ shadowed if present)_ Jar file instead of the other one.

**Comment by jpenilla** [comment]
You can use the runPaper accessor instead of extensions.configure.
But you should not manually add task output paths. See https://docs.gradle.org/current/userguide/lazy_configuration.html#lazy_properties
`reobfJar.flatMap { it.outputJar }` is what you should add to the pluginJars ConfigurableFileCollection using the from method

**Comment by ineanto** [comment]
I've been a long lasting user of Maven and I've only made the switch to Gradle about a year and a half ago. Thank you for teaching me stuff!
